services:
  frontend:
    build: ./ntu-training-management-system-fe
    container_name: ntu-frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=120
    ports:
      - "5173:5173"
    volumes:
      - ./ntu-training-management-system-fe:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build: ./ntu-training-management-system-be
    container_name: ntu-backend
    environment:
      - APP_AUTO_MIGRATE=true
      - APP_AUTO_SEED=false
      - DB_WAIT_TIMEOUT_SECONDS=60
      - DB_WAIT_INTERVAL_SECONDS=2
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=ntu_training_management
      - DB_USERNAME=postgres
      - DB_PASSWORD=123456789
    ports:
      - "8000:8000"
    volumes:
      - ./ntu-training-management-system-be:/var/www
      - /var/www/vendor
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: ntu-postgres
    restart: always
    environment:
      POSTGRES_DB: ntu_training_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: